name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node and deps
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build app (creates dist/)
        run: npm run build

      - name: Prepare package directory
        run: |
          set -e
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF##refs/tags/}
            VERSION=${VERSION#v}
          else
            VERSION="pr-${GITHUB_SHA:0:7}"
          fi

          if [[ "${{ matrix.arch }}" == "x64" ]]; then
            PKG_ARCH="x86_64"
          else
            PKG_ARCH="aarch64"
          fi

          # Prepare dist artifact directory if not already
          mkdir -p dist

          # Prepare batocera-pkg structure
          mkdir -p batocera-pkg/userdata/roms/ports

          # Copy built app, launcher, media, gamelist.xml, etc. as needed
          # Adjust these cp/mv lines for your actual build output/artifacts and config
          cp -r dist/linux-${{ matrix.arch }}-unpacked/* batocera-pkg/userdata/roms/ports/ || true
          cp -r resources/batocode-arcade.sh batocera-pkg/userdata/roms/ports/ || true
          cp -r resources/gamelist.xml batocera-pkg/userdata/roms/ports/ || true
          cp -r resources/batocode-arcade.png batocera-pkg/userdata/roms/ports/ || true

          # Create .PKGINFO (required for Batocera pacman)
          cat <<EOF > batocera-pkg/.PKGINFO
          pkgname = batocode-arcade
          pkgver = ${VERSION}
          pkgdesc = Batocode Arcade build for Batocera
          arch = ${PKG_ARCH}
          group = ports
          packager = github-actions
          url = https://github.com/${GITHUB_REPOSITORY}
          EOF

      - name: Create tarball
        id: create_tarball
        run: |
          set -e
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF##refs/tags/}
            VERSION=${VERSION#v}
          else
            VERSION="pr-${GITHUB_SHA:0:7}"
          fi

          TAR_NAME="batocode-arcade-${VERSION}-${{ matrix.arch }}.tar.gz"
          tar -czf "dist/$TAR_NAME" -C dist "linux-${{ matrix.arch }}-unpacked"
          echo "tarball_path=dist/$TAR_NAME" >> $GITHUB_OUTPUT
          echo "tarball_name=$TAR_NAME" >> $GITHUB_OUTPUT

      - name: Create Batocera Pacman package
        id: create_pacman_pkg
        run: |
          set -e
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF##refs/tags/}
            VERSION=${VERSION#v}
          else
            VERSION="pr-${GITHUB_SHA:0:7}"
          fi

          if [[ "${{ matrix.arch }}" == "x64" ]]; then
            PKG_ARCH="x86_64"
          else
            PKG_ARCH="aarch64"
          fi

          tar --zstd -cf "batocode-arcade-${VERSION}-${PKG_ARCH}.pkg.tar.zst" -C batocera-pkg .
          echo "pacman_pkg_path=batocode-arcade-${VERSION}-${PKG_ARCH}.pkg.tar.zst" >> $GITHUB_OUTPUT

      - name: Create pacman repo (optional)
        run: |
          set -e
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF##refs/tags/}
            VERSION=${VERSION#v}
          else
            VERSION="pr-${GITHUB_SHA:0:7}"
          fi

          if [[ "${{ matrix.arch }}" == "x64" ]]; then
            PKG_ARCH="x86_64"
          else
            PKG_ARCH="aarch64"
          fi

          mkdir -p pacman-repo
          cp "batocode-arcade-${VERSION}-${PKG_ARCH}.pkg.tar.zst" pacman-repo/
          cd pacman-repo
          sudo apt-get update && sudo apt-get install -y arch-install-scripts
          repo-add batocode-arcade.db.tar.gz "batocode-arcade-${VERSION}-${PKG_ARCH}.pkg.tar.zst"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: batocode-arcade-${{ matrix.arch }}-${{ github.event_name == 'pull_request' && format('pr-{0}', github.sha) || github.ref_name }}
          path: |
            dist/*.tar.gz
            *.pkg.tar.zst
            pacman-repo/*
          retention-days: 5