name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo pacman -Sy --noconfirm base-devel git devtools

      - name: Set environment variables
        id: vars
        run: |
          set -e
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=${GITHUB_REF_NAME#v}
          else
            VERSION="pr-${GITHUB_SHA::7}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tarball
        run: |
          set -e
          cd dist
          TAR_NAME="batocode-arcade-${VERSION}-${{ matrix.arch }}.tar.gz"
          tar -czf "$TAR_NAME" "batocode-arcade-linux-${{ matrix.arch }}-${VERSION}"
          echo "tarball_path=$PWD/$TAR_NAME" >> $GITHUB_OUTPUT
          echo "tarball_name=$TAR_NAME" >> $GITHUB_OUTPUT

      - name: Create pacman package
        run: |
          set -e
          PKG_ARCH="${{ matrix.arch == 'x64' && 'x86_64' || 'aarch64' }}"
          cd batocera-pkg
          tar --zstd -cf ../batocode-arcade-${VERSION}-${PKG_ARCH}.pkg.tar.zst .

      - name: Create pacman repo
        run: |
          set -e
          PKG_ARCH="${{ matrix.arch == 'x64' && 'x86_64' || 'aarch64' }}"
          mkdir -p pacman-repo
          cp batocode-arcade-${VERSION}-${PKG_ARCH}.pkg.tar.zst pacman-repo/
          cd pacman-repo
          sudo pacman -Sy --noconfirm devtools
          repo-add batocode-arcade.db.tar.gz batocode-arcade-${VERSION}-${PKG_ARCH}.pkg.tar.zst

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: batocode-arcade-${{ matrix.arch }}-${{ github.event_name == 'pull_request' && format('pr-{0}', github.sha) || github.ref_name }}
          path: |
            dist/*.tar.gz
            *.pkg.tar.zst
            pacman-repo/*
          retention-days: 5