name: Build App forLinux ,  and Update Pacman Repo

on:
  push:
    tags:
      - 'v*'

jobs:
  prepare-version:
    runs-on: ubuntu-24.04
    steps:
      - name: Strip the version
        id: strip_version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.strip_version.outputs.version }}

  build-linux:
    needs: prepare-version
    uses: ./.github/workflows/build-linux.yml
    with:
      version: ${{ needs.prepare-version.outputs.version }}

  publish-release:
    needs: build-linux
    runs-on: ubuntu-24.04
    steps:
      - name: Download x86_64 tarball
        uses: actions/download-artifact@v4
        with:
          name: release-tarball-x86_64
          path: ./artifacts

      - name: Download aarch64 tarball
        uses: actions/download-artifact@v4
        with:
          name: release-tarball-aarch64
          path: ./artifacts

      - name: Upload both release tarballs to single GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-repo-db:
    needs: build-linux
    runs-on: ubuntu-24.04
    steps:
      - name: Download pacman-repo artifacts from all archs
        uses: actions/download-artifact@v4
        with:
          pattern: pacman-pkg-*
          path: ./pacman-repo
          merge-multiple: false

      - name: Prepare per-arch repo-db directories
        run: |
          set -e
          mkdir -p aarch64 x86_64
          cp pacman-repo/pacman-pkg-aarch64/*.pkg.tar.zst aarch64/
          cp pacman-repo/pacman-pkg-x86_64/*.pkg.tar.zst x86_64/

      - name: Re-create repo-add database for aarch64
        run: |
          cd aarch64
          rm -f *.db* *.files*
          docker run --rm -v "$PWD":/repo -w /repo archlinux:latest \
            bash -c "repo-add batocode-arcade.db.tar.gz *.pkg.tar.zst"
          echo "== aarch64 DB architectures =="
          tar -xOf batocode-arcade.db.tar.gz | grep '^arch =' || true
          echo "=============================="

      - name: Re-create repo-add database for x86_64
        run: |
          cd x86_64
          rm -f *.db* *.files*
          docker run --rm -v "$PWD":/repo -w /repo archlinux:latest \
            bash -c "repo-add batocode-arcade.db.tar.gz *.pkg.tar.zst"
          echo "== x86_64 DB architectures =="
          tar -xOf batocode-arcade.db.tar.gz | grep '^arch =' || true
          echo "============================"

      - name: Upload final pacman repos for pages (per-arch)
        uses: actions/upload-artifact@v4
        with:
          name: pacman-repo-final
          path: |
            aarch64/*
            x86_64/*

  deploy-repo:
    needs: update-repo-db
    runs-on: ubuntu-24.04
    steps:
      - name: Download pacman repo dbs
        uses: actions/download-artifact@v4
        with:
          name: pacman-repo-final
          path: ./pacman-repo

      - name: Deploy Pacman Repos to GitHub Pages (per-arch folders)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./pacman-repo
