name: Build Test Packages

on:
  pull_request:
    branches:
      - develop

jobs:
  prepare-version:
    runs-on: ubuntu-24.04
    steps:
      - name: Strip the version
        id: strip_version
        run: echo "version=PR-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.strip_version.outputs.version }}

  build-linux:
    needs: prepare-version
    uses: ./.github/workflows/build-linux.yml
    with:
      version: ${{ needs.prepare-version.outputs.version }}